base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
]

todo/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from todo import views


app_name = "todo"
urlpatterns = [
    path('', views.TaskListView.as_view(), name="task-list" ),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login" ),
    path('logout/', auth_views.LogoutView.as_view(), name="logout" ),
    path('registration/', views.UserCreateView.as_view(), name="registration" ),
    path('create/', views.TaskCreateView.as_view(), name="task-create" ),
    path('delete/<int:pk>', views.TaskDeleteView.as_view(), name="task-delete" ),
    path('update/<int:pk>', views.TaskUpdateView.as_view(), name="task-update" ),

]

todo/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created"]

todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 

from todo.models import Task


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def clean(self):
        #cleaned_data = super().clean()
        print(self.cleaned_data)
        username = self.cleaned_data['username']
        if username and User.objects.filter(username__iexact=username).exists():
            self.add_error('username', 'A user with that username already exists.')
        #return cleaned_data

        

class TaskCreateForm(forms.ModelForm):

    class Meta:
        model=Task
        fields=['title', 'description', 'complete']

class TaskUpdateForm(forms.ModelForm):

    class Meta:
        model=Task
        fields=['title', 'description', 'complete']

class TaskSearchForm(forms.Form):
    search = forms.CharField(max_length=250)

todo/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView,DeleteView,UpdateView
from django.urls import reverse_lazy
#from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import User 
from django.contrib.auth.mixins import UserPassesTestMixin

from todo.forms import RegistrationForm, TaskCreateForm,TaskUpdateForm
#from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth import login
# Imports for Reordering Feature
#from django.views import View
#from django.shortcuts import redirect
#from django.db import transaction

from .models import Task


class TaskListView(ListView):
    model = Task
    template_name = 'todo/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user.id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        
        context['count'] = queryset.filter(complete=False, user=self.request.user.id).count()

        search_input = self.request.GET.get('search', None)
        if search_input:
            context['tasks'] = queryset.filter(title__contains=search_input)

        context['search_input'] = search_input

        return context

class UserCreateView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('todo:login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs) 

    def form_valid(self, form):
        # Success message 
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Registration was successful'
        ) 
        return super().form_valid(form)



class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    success_url = reverse_lazy('todo:task-list')
    form_class=TaskCreateForm
    template_name='todo/task_create.html'

    def form_valid(self, form):
        form.instance.user=self.request.user

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Task Created!'
        ) 
        return super().form_valid(form)

        
class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('todo:task-list')
    template_name='todo/task_confirm_delete.html'
    context_object_name = 'task'

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.ERROR,
            'Task Deleted!'
        )         
        return super().form_valid(form)



class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    success_url = reverse_lazy('todo:task-list')
    form_class=TaskUpdateForm
    template_name='todo/task_update.html'

    def form_valid(self, form):
        #form.instance.user=self.request.user

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Task Updated!'
        ) 
        return super().form_valid(form)


    def test_func(self):
        return self.request.user == self.get_object().user

templates/accounts/login.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}

{% block title %}
   Login
{% endblock %}

{% block content %}
    <div class="header-bar">
        <h1>Login</h1>
    </div>

    <div class="card-body">

        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} text-center">
                {{ message }}
            </div>
        {% endfor %}
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex flex-column">
                <input class="button mb-2" type="submit" value="Login">
                <small class="text-muted" >Don't have an account? <a href="{% url 'todo:registration' %}">Register</a></small >
            </div>
        </form>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}

{% block title %}
   Register
{% endblock %}


{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex flex-column">
                <input class="button mb-2" type="submit" value="Register">
                <small class="text-muted" >Don't have an account? <a href="{% url 'todo:login' %}">Login</a></small >
            </div>
        </form>
    </div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Todo App
        {% endblock %}
    </title>
    
    {% comment %} bootstrap {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    {% comment %} custom css {% endcomment %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>

    <div class="box">
        {% block content %} 
        {% endblock content %}
    </div>


</body>
</html>

templates/todo/task_confirm_delete.html
{% extends '../base.html' %} 
{% load crispy_forms_tags %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'todo:task-list' %}">&#8592; Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this task? <b>"{{task.title}}"</b> </p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>

{% endblock content %}

templates/todo/task_create.html
{% extends '../base.html' %} 
{% load crispy_forms_tags %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'todo:task-list' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form|crispy}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>

{% endblock content %}

templates/todo/task_list.html
{% extends '../base.html' %} 

{% block content %}

<div class="header-bar">
    <div>
        {% if request.user.is_authenticated %}
            <h3>Hello {{request.user|title}}</h3>
            <h4 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h4>
        {% else %}
            <h3>Login to view your tasks</h3>
        {% endif %}

    </div>

    {% if request.user.is_authenticated %}
        <a href="{% url 'todo:logout' %}">Logout</a> 
    {% else %}
        <a href="{% url 'todo:login' %}">Login</a>  
    {% endif %}
</div>

{% if request.user.is_authenticated %}

    {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == "error" %}alert-danger{% else %} alert-{{ message.tags }} {% endif %}  text-center">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}


    <div id="search-add-wrapper" class="d-flex justify-content-between mb-3">
        <form method="GET" class="">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search Task" name="search">
                <button class="btn btn-outline-dark" type="submit" id="button-addon2">Search</button>
            </div>
        </form>
        <a id="add-link" class="" href="{% url 'todo:task-create' %}">
            <i class="bi bi-plus-circle-dotted"></i>
        </a>
    </div>
{% endif %}


<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
        <div class="task-wrapper" data-position="{{task.pk}}">
            <div class="task-title">
                {% if task.complete %}
                    <div class="d-flex">
                        <div class="task-complete-icon"></div>
                        <div class="d-flex flex-column ms-2">
                            <i><s><a href="{% url 'todo:task-update' task.id %}">{{task.title}}</a></s></i>
                            <small class="text-muted">{{task.description}}</small>
                        </div>
                    </div>
                {% else %}
                    <div class="d-flex">
                        <div class="task-incomplete-icon"></div>
                        <div class="d-flex flex-column ms-2">
                            <a href="{% url 'todo:task-update' task.id %}">{{task.title}}</a> 
                            <small class="text-muted">{{task.description}}</small>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="task-controls p-3">
                <a class="delete-link" href="{% url 'todo:task-delete' task.id %}">
                    <i class="bi bi-x"></i>
                </a>
            </div>
        </div>
    {% empty %}
        {% if search_input %}
            <div class="py-3 lh-1" style="text-align: center;">
                <h3>No results for your search.</h3>
                <h3 style="color: #e53935;">{{search_input}}</h3>
            </div>
        {% else %}
            <div class="py-3 lh-1" style="text-align: center;">
                <h3>No new tasks are created.</h3>
                <h3 style="color: #e53935;">Create a New task ! </h3>
            </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock content %}

templates/todo/task_update.html
{% extends '../base.html' %} 
{% load crispy_forms_tags %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'todo:task-list' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form|crispy}}
        <input class="button" type="submit" value="Update">
    </form>
</div>

{% endblock content %}